### ISSUE TITLE
Consider making underlying google protobuf or scalabuf version configurable

### ISSUE THREAD

**Issue by gmalouf** [sbt/sbt-scalabuff#1]
It would be nice if the plugin allowed one to set the underlying scalabuf or google protobuf versions that they would like to use configurable.  As an example, google just released protobuf version 2.5, but a lot of people for compatibility reasons need to stick to 2.4.1.  Rather than having two branches of the plugin, a configurable version would be nice.

**Comment by aloiscochard** [comment]
The scalabuff version is parameterized as you can see here
https://github.com/sbt/sbt-scalabuff/blob/master/src/main/scala/ScalaBuffPlugin.scala#L15

with a default value of 1.1.1:
https://github.com/sbt/sbt-scalabuff/blob/master/src/main/scala/ScalaBuffPlugin.scala#L20

I don't see any reason for branching the plugin... protobuf version is not paraeterized as it's a dependency of scalabuff, you can anyway override it in your project...

I close this issue as obviously the OP didn't realize the plugin support dynamic version of scalabuff, if you think there is still a problem regarding versioning please open an other ticket.
