### ISSUE TITLE
java.lang.NoClassDefFoundError: net/sandrogrzicic/scalabuff/compiler/ScalaBuff

### ISSUE THREAD

**Issue by divijan** [sbt/sbt-scalabuff#5]
Not sure about the cause of this, so I call this issue by its main symptom. I see this error when sbt tries to compile my .proto files in a simple project. It is configured as per the readme. I am running Fedora 16 x64, OpenJDK 1.6 and sbt 0.12.3. To investigate the problem, I downloaded the source of sbt-scalabuff and made it print a list used as a second argument for `Fork.java` in scalabuff.ScalaBuffPlugin.process method. Then I packaged sbt-scalabuff, used it as an unmanaged dependency for my project's build definition and did `sbt compile` on my project (let **X** denote a sequence of actions described in this sentence). The classpath argument for java was empty. So I put scalabuff compiler jar from sbt cache into my project's lib and hardcoded classpath pointing to it into sbt-scalabuff. After that I did **X** and sbt found the scalabuff compiler main class, but could not find scala.Function1 class. So it seems likely that the cause of the problem is the empty classpath argument. Feel free to comment on this issue and request any details you need so that we can work together to resolve this.

**Comment by SandroGrzicic** [comment]
I'd love to help, but I don't really think I can do much since this is directly related to the SBT plugin itself.

**Comment by rssh** [comment]
btw, can you add self-contained attaced as  archive or as github project ?

**Comment by divijan** [comment]
There you go: https://github.com/divijan/scalabuff_test

**Comment by rssh** [comment]
I found error in you example: 

<pre>
  settings = Defaults.defaultSettings ++
            scalabuffSettings ++
            Seq(scalaVersion := "2.10.0",
                name := "scalabuff_test",
                libraryDependencies := Seq(
                   "net.databinder.dispatch" %% "dispatch-core" % "0.10.0"
                )
            )
</pre>

here you set  libraryDependencies after setting scalabuff default settings.
But scalabuff default settings modify libraryDependencies.  Changing setting dependencies to

<pre>
                ....
                libraryDependencies ++= Seq(
                   "net.databinder.dispatch" %% "dispatch-core" % "0.10.0"
                )
  </pre>

do the trick

(example at https://github.com/rssh/scala-training-materials/tree/master/protobuf-example )

I guess, sbt-scalabuff issue can be closed.

**Comment by divijan** [comment]
rssh is correct. Sorry for the stir-up.
